name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        cat <<EOF > .env
        NODE_ENV=production
        PORT=5000
        PG_DB=${{ secrets.PG_DB }}
        PG_HOST=${{ secrets.PG_HOST }}
        PG_PORT=${{ secrets.PG_PORT }}
        PG_USER=${{ secrets.PG_USER }}
        PG_PASSWORD=${{ secrets.PG_PASSWORD }}
        SESSION_KEY=${{ secrets.SESSION_KEY }}
        EOF
      shell: bash
    - run: make install
    - run: make check
    - run: make build
